// Generated by lsdsim. Do not edit: changes are overwritten.
#include "fun_head_fast.h"

MODELBEGIN

EQUATION( "Z" )
RESULT( ( ( 2.0 * V( "a" ) ) - ( 3.0 * V( "b" ) ) ) + 7.0 )

MODELEND

void close_sim( void )
{
}
